version: '3'
services:
  cakemix:
    image: ghcr.io/wonder-wonder/cakemix:latest
    container_name: cakemix
    depends_on:
      - cakemixpg
    # env_file:
      # - cakemix.env
      # - sendgrid.env
    networks:
      - cakemix-network
    ports:
      - 8081:8081
    restart: always
    volumes:
      - cmdat:/var/lib/cakemix
      - cmlog:/var/log/cakemix
      # or if you bind your dir, you can use the following
      # - /path/to/cmdat:/var/lib/cakemix
      # - /path/to/cmlog:/var/log/cakemix

  cakemixpg:
    image: postgres
    container_name: cakemixpg
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - cakemix-network
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - cmdb:/var/lib/postgresql/data
      # or if you bind your dir, you can use the following
      # - /path/to/cmdb:/var/lib/postgresql/data

volumes:
  cmdat:
  cmlog:
  cmdb:

networks:
  cakemix-network: